spring.application.name=Carrera
server.port=9092

#Configuracion de la BD de carrera, una por cada microservicio
spring.datasource.url=jdbc:mysql://localhost:3306/multitriatlonpacarrera
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n 
logging.level.org.hibernate.SQL=debug

#Url del WebClient para el llamado a las API's triatleta y categoria
webclient.url.triatleta=http://localhost:9091/api/triatletas
webclient.url.categoria=http://localhost:9093/api/categorias